### ISSUE TITLE
destroyclick not working

### ISSUE THREAD

**Issue by diegoviador** [andresclua/boostify#2]
When I try to set a destroyclick, It shows the next error on the browser:

![image](https://github.com/andresclua/boostify/assets/160519480/0cab6c7e-84b0-4155-8487-3f5062350998)

This is an example snippet that triggers the error on my project:

```
this.boostify.click({
    debug:true,
    element:document.getElementById('item-1'),
    callback: () =>{
        console.log('item 1 was clicked')
    }
})

setTimeout(() => {
    this.boostify.destroyclick({element:document.getElementById('item-2')});
},4200)
```

**Comment by andresclua** [comment]
issue was fixed on version 13
